Moved preprocessing of data to this library
REMLA24-Team-5/lib-ml pull request #5
Opened 2024-05-07 16:25 UTC by SagaRut

The problem is that this class has to have a tokenizer and a label encoder which need to be trained on the same data that the model is trained on so it will have to have access to data...which is now being downloaded from google drive. This is obviously not ideal for a library...but idk what else to do. Nothing else about the preprocessing can be separated into this library. Also when we refactor this out of model-train the data will be downloaded twice...Additionally now the data is always downloaded and never cached...

2024-05-09 12:13 UTC, Timdnb requested changes

2024-05-09 12:13 UTC, Timdnb commented on lib-ml/pre_process.py
can't we put the dataset in the init of the class? then wherever the preprocess is used, we first download the data and pass that to the preprocessing class

2024-05-09 12:13 UTC, Timdnb commented on lib-ml/pre_process.py
and about having to download from gdrive, don't think there is much of a choice, otherwise we would have to download from kaggle or whatever, we need to download it at some point

2024-05-09 12:13 UTC, Timdnb commented on requirements.txt
is this still needed when we're using poetry?

2024-05-10 05:58 UTC, SagaRut commented on lib-ml/pre_process.py
Yeah we could pass it through when constructing if you think that is better, but either way we would have to download when constructing, should I still change it to that?

2024-05-10 05:58 UTC, SagaRut commented on requirements.txt
Ah no forgot to delete this

2024-05-10 09:09 UTC, Timdnb commented on lib-ml/pre_process.py
We could do that, then in model-training, I'd update the get_data.py function to simply download from gdrive (and do nothing else), then all content of preprocess.py can be removed and put the Preprocess class from this lib-ml there, with the dataset as input. Then I guess the dvc pipeline can stay more or less the same. Does all of that makes sense?

2024-05-10 09:11 UTC, Timdnb commented on lib-ml/pre_process.py
Or do we want to completely delete the get_data.py and preprocess.py files, if yes then downloading the dataset should stay within the Prepocess class and we just put that at the start of the train.py file.

2024-05-13 15:27 UTC, SagaRut commented on lib-ml/pre_process.py
I think taking it in as a parameter is the best option, changed it to that

2024-05-13 15:58 UTC, Timdnb commented on lib-ml/pre_process.py
where will you know put the

train = [line.strip() for line in open('data/train.txt', "r", encoding="utf-8").readlines()[1:]]

lines? because that should still be in preprocessing right?

2024-05-13 16:03 UTC, SagaRut commented on lib-ml/pre_process.py
Well that is just creating the raw python lists from txt files and since the txt files can't be taken in as parameters into this class by themselves I think its fine if that is done when downloading

2024-05-13 16:08 UTC, Timdnb commented on lib-ml/pre_process.py
All good with me, go ahead and merge then!

2024-05-13 16:08 UTC, Timdnb approved these changes

2024-05-13 16:10 UTC, merged